server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost/user_list
    username: postgres
    password: 2343480
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
